export const FETCH_EXERCISES = 'FETCH_EXERCISES';
export const DELETE_EXERCISE = 'DELETE_EXERCISE';
export const START_DELETE_EXERCISE = 'START_DELETE_EXERCISE';
export const CREATE_EXERCISE = 'CREATE_EXERCISE';
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE';
